### ISSUE TITLE
pack errors on python 3.7.0

### ISSUE THREAD

**Issue by slawdos** [panzi/u4pak#15]
Z:\Mods\modded\Image0\echo\content\paks>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

Z:\Mods\modded\Image0\echo\content\paks>u4pak.py pack new.pak Echo
Traceback (most recent call last):
  File "Z:\Mods\modded\Image0\echo\content\paks\u4pak.py", line 1694, in <module>
    main(sys.argv[1:])
  File "Z:\Mods\modded\Image0\echo\content\paks\u4pak.py", line 1654, in main
    pack(stream,args.files,args.mount_point,args.archive_version,compFmt,callback=callback)
  File "Z:\Mods\modded\Image0\echo\content\paks\u4pak.py", line 798, in pack
    files.sort(cmp=strcoll)
TypeError: 'cmp' is an invalid keyword argument for sort()

On python 2.7 work fine.

**Comment by panzi** [comment]
Ok, I had a couple of minutes time to fix this WITHOUT TESTING. No time for that. If you could check if this works for you that would be great. :)
