### ISSUE TITLE
Error packing files: 'Namespace' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by Notexe** [panzi/u4pak#32]
```
Traceback (most recent call last):
  File "u4pak.py", line 1732, in <module>
    main(sys.argv[1:])
  File "u4pak.py", line 1686, in main
    callback=callback, encoding=args.encoding)
AttributeError: 'Namespace' object has no attribute 'encoding'
```

Tried with python2 and python3, same issue. Not really sure what the problem is.

**Comment by panzi** [comment]
Ok, I think I fixed it with this commit: ef6af847361fa53a877fa4e8ec85dae8772887a3 Can you try again? Thank you!

**Comment by Notexe** [comment]
Issue appears to be resolved. Thank you.

**Comment by panzi** [comment]
Awesome!
